employee_data_window = Window(app, title = "Employee Data")
employee_data_window.hide()
text_blank = Text(app, text=" ")
text_blank = Text(app, text=" ")
messages_title =  Text(employee_data_window, text = "Employee Data")
box2 = Box(employee_data_window, layout = "grid", border = False)
box3 = Box(box2, border = False, grid = [0,3])
box4 = Box(box2, border = False, grid = [1,3])
box5 = Box(box2, border = False, grid = [2,3])
box6 = Box(box2, border = False, grid = [0,4])
box7 = Box(box2, border = False, grid = [1,4])
box8 = Box(box2, border = False, grid = [2,4])
box9 = Box(box2, border = False, grid = [0,5])
box10 = Box(box2, border = False, grid = [1,5])
box11 = Box(box2, border = False, grid = [2,5])
marlon_picture = Picture(box3, image="marlonbetter.jpg", height = 150, width = 150)
ash_picture = Picture(box4, image="ashbetter.jpg", height = 150, width = 150)
jack_picture = Picture(box5, image="jackbetter.jpg", height = 150, width = 150)
sale_data = PushButton(box10, text = "View Data", command = open_getsale)
emp1_textbox = TextBox(box6, width = 20)
emp2_textbox = TextBox(box7, width = 20)
emp3_textbox = TextBox(box8, width = 20)

